CREATE DATABASE practice_qna;
USE PRACTICE_qna;
select *
from sales_data;

# Calculate the Total sales for each order.
select Product,
Quantity * Price as Total_Sales
from sales_data;

# Find the Top orders based on Total sales.
select *,
Quantity * Price as Total_Sales
from sales_data
order by Total_Sales desc
limit 5;

# Which city generated highest revenue.
SELECT City,
SUM(Quantity * Price) AS Revenue
FROM sales_data
GROUP BY City
ORDER BY Revenue DESC
LIMIT 1;

# Find the average product price for each category
SELECT Category,
AVG(Quantity * Price) as Average_Price
FROM sales_data
GROUP BY Category;

# Count the total number of order plaed in each city
SELECT City,
Count(*) as Total_Order
FROM sales_data
GROUP BY City

# Find all customers who have purchased Electronics products.
SELECT DISTINCT Customer
FROM sales_data
WHERE Category = "Electronics";

# Display categories whose average rating is grater than 4.5.
Select Category,
AVG(Rating) AS AVG_Rating
FROM sales_data
GROUP BY Category
HAVING AVG(Rating) > 4.5;

# Find the 2th highest priced product.
SELECT Product, Price
FROM sales_data
ORDER BY Price DESC
LIMIT 1 OFFSET 1;

SELECT Product, Price
FROM sales_data
ORDER BY Price DESC
LIMIT 1 , 1;

# Rank all products based on Price.
SELECT Product, Price,
RANK() OVER(ORDER BY Price DESC) AS Product_Rank
FROM sales_data;

# Find the total revenue generated by each category.
SELECT Category,
SUM(Quantity * Price) AS Revenue
FROM sales_data
GROUP BY Category;

# Find the Customer who generate the highest revenue.
SELECT Customer,
SUM(Quantity * Price) AS Revenue
FROM sales_data
GROUP BY Customer
ORDER BY Revenue DESC
LIMIT 1;

# Display the total quantity sold for each product.
SELECT Product,
SUM(Quantity) AS total_quantity
FROM sales_data
GROUP BY Product;

# Find Products whose total sales are greater than 50000.
SELECT Product,
SUM(Quantity * Price) AS Total_Sales
FROM sales_data
GROUP BY Product
HAVING SUM(Quantity * Price) > 50000;

# Display the top 3 customers based on revenue.
SELECT Customer,
SUM(Quantity * Price) AS Revenue
FROM sales_data
GROUP BY Customer
ORDER BY Revenue DESC
LIMIT 3;

# Find the total numbers of products sold in each category.
SELECT Category,
SUM(Quantity) AS Product_Sold
FROM sales_data
GROUP BY Category;

# Find the maxmimum , minimum, and average price for each category.
SELECT Category,
	MAX(Price) AS Max_Price,
	MIN(Price) AS Min_Price,
	AVG(Price) AS Avg_Price
FROM sales_data
GROUP BY Category;

# Find customer who have placed more than one order.
SELECT Customer,
COUNT(Order_ID) AS Total_Order
FROM sales_data
GROUP BY Customer
HAVING COUNT(Order_ID) > 1;

# Display all orders where the price is higher than the average price.
SELECT *
FROM sales_data
WHERE Price > (
SELECT AVG(Price)
	FROM sales_data);

# Assign a row number to each order based on price (highest first).
SELECT Order_ID, Product, Price,
ROW_NUMBER() OVER(Order by Price DESC) AS Row_num
FROM sales_data;

# Display a new column called price_category: price>= 20000-High, Price>= 10000-Medium otherwise - low
SELECT Product,
		Price,
		CASE 
        WHEN Price >= 20000 THEN "High"
        WHEN Price >= 10000 THEN "MEDIUM"
        ELSE "LOW"
	END AS Price_Category
FROM sales_data;

# IT'S TIME OT PRACTICE JOINS *****************************************************8

# Display customer name, city , product, and price by joining both tables.
SELECT C.Customer,
	   C.City,
       S.Price
FROM customers c
INNER JOIN Sales_data s
ON c.Customer_ID = s.Customer_ID;

# Display all customers, even if they have not placed any orders.

SELECT c.Customer,
       s.Product
FROM customers c
LEFT JOIN sales_data s
ON c.Customer_ID = s.Customer_ID;

# Rank customers based on total revenue.

SELECT Customer,
       SUM(Quantity * Price) AS Revenue,
       RANK() OVER(ORDER BY SUM(Quantity * Price) DESC) AS Customer_Rank
FROM sales_data
GROUP BY Customer;

# Give Dense Rank based on Price.

SELECT Product,
       Price,
       DENSE_RANK() OVER(ORDER BY Price DESC) AS Rank_No
FROM sales_data;

# Give row numbers to all orders according to rating.

SELECT Order_ID,
       Rating,
       ROW_NUMBER() OVER(ORDER BY Rating DESC) AS Row_Num
FROM sales_data;

# Find customers whose revenue is greater than ₹50,000 using a CTE.

WITH Revenue AS
(
SELECT Customer,
SUM(Quantity*Price) AS Total_Revenue
FROM sales_data
GROUP BY Customer
)

SELECT *
FROM Revenue
WHERE Total_Revenue > 50000;

# Find the product having the highest price.

SELECT Product,
       Price
FROM sales_data
WHERE Price =
(
SELECT MAX(Price)
FROM sales_data
);

#  Display Electronics products with a rating greater than 4.5.

SELECT *
FROM sales_data
WHERE Category='Electronics'
AND Rating > 4.5;

# Find the city with the maximum number of customers.

SELECT City,
       COUNT(DISTINCT Customer) AS Total_Customers
FROM sales_data
GROUP BY City
ORDER BY Total_Customers DESC
LIMIT 1;

#  Find the Top 3 highest-selling products based on revenue.

SELECT Product,
       SUM(Quantity*Price) AS Revenue
FROM sales_data
GROUP BY Product
ORDER BY Revenue DESC
LIMIT 3;

#  Display the next order's price for every order.
SELECT Order_ID,
       Price,
       LEAD(Price) OVER(ORDER BY Order_ID) AS Next_Price
FROM sales_data;

#  Display the previous order's price for every order.
SELECT Order_ID,
       Price,
       LAG(Price) OVER(ORDER BY Order_ID) AS Previous_Price
FROM sales_data;

#  Calculate the running total of revenue.
SELECT Order_ID,
       Quantity * Price AS Sales,
       SUM(Quantity * Price)
       OVER(ORDER BY Order_ID) AS Running_Total
FROM sales_data;

#  Rank products within each category based on price.
SELECT Product,
       Category,
       Price,
       RANK() OVER(PARTITION BY Category ORDER BY Price DESC) AS Rank_No
FROM sales_data;

#  Find the customer who generated the maximum revenue.
SELECT Customer,
       SUM(Quantity * Price) AS Revenue
FROM sales_data
GROUP BY Customer
ORDER BY Revenue DESC
LIMIT 1;

#  Find each product's contribution (%) to total revenue.
SELECT Product,
       SUM(Quantity * Price) AS Revenue,
       ROUND(
           SUM(Quantity * Price) * 100 /
           (SELECT SUM(Quantity * Price) FROM sales_data),
           2
       ) AS Revenue_Percentage
FROM sales_data
GROUP BY Product;

#  Find the third highest price.
SELECT DISTINCT Price
FROM sales_data
ORDER BY Price DESC
LIMIT 1 OFFSET 2;

SELECT DISTINCT Price
FROM sales_data
ORDER BY Price DESC
LIMIT 1 , 2;

#  Display all customers whose names start with the letter 'A'.
SELECT *
FROM sales_data
WHERE Customer LIKE 'A%';

#  Find products whose prices are between ₹10,000 and ₹20,000.
SELECT Product,
       Price
FROM sales_data
WHERE Price BETWEEN 10000 AND 20000;

#  Find duplicate customers.
SELECT Customer,
       COUNT(*) AS Total
FROM sales_data
GROUP BY Customer
HAVING COUNT(*) > 1;

#  Which city generated the highest total revenue?
SELECT City,
       SUM(Quantity * Price) AS Revenue
FROM sales_data
GROUP BY City
ORDER BY Revenue DESC
LIMIT 1;

#  Which category generated the highest revenue?
SELECT Category,
       SUM(Quantity * Price) AS Revenue
FROM sales_data
GROUP BY Category
ORDER BY Revenue DESC
LIMIT 1;

#  Find the product with the highest average rating.
SELECT Product,
       AVG(Rating) AS Avg_Rating
FROM sales_data
GROUP BY Product
ORDER BY Avg_Rating DESC
LIMIT 1;

#  Find the customer who generated the highest revenue in each city.
SELECT City,
       Customer,
       Revenue
FROM (
    SELECT City,
           Customer,
           SUM(Quantity * Price) AS Revenue,
           RANK() OVER(PARTITION BY City ORDER BY SUM(Quantity * Price) DESC) AS rnk
    FROM sales_data
    GROUP BY City, Customer
) t
WHERE rnk = 1;

#  Calculate the total revenue for each rating.
SELECT Rating,
       SUM(Quantity * Price) AS Revenue
FROM sales_data
GROUP BY Rating
ORDER BY Rating DESC;

#  Find the highest-priced product in every category.
SELECT Category,Product,Price
FROM (SELECT Category,Product,Price,
           RANK() OVER(PARTITION BY Category ORDER BY Price DESC) AS rnk
    FROM sales_data
) t
WHERE rnk = 1;
#  Calculate the average order value.
SELECT AVG(Quantity * Price) AS Average_Order_Value
FROM sales_data;

#  Show orders whose sales are above the average sales.
SELECT *,
       Quantity * Price AS Sales
FROM sales_data
WHERE Quantity * Price >
(
    SELECT AVG(Quantity * Price)
    FROM sales_data
);
#  Find how many products each customer has purchased.
SELECT Customer,
       SUM(Quantity) AS Total_Items
FROM sales_data
GROUP BY Customer
ORDER BY Total_Items DESC;

#  Find the top 5 customers based on total revenue and display their rank.
SELECT Customer,
       SUM(Quantity * Price) AS Revenue,
       RANK() OVER(ORDER BY SUM(Quantity * Price) DESC) AS Customer_Rank
FROM sales_data
GROUP BY Customer
LIMIT 5;

USE data_analytics_project;

CREATE DATABASE sales_db;
USE sales_db;

SELECT * FROM sales_data;

-- Q1. What is the total revenue generated b male vs female customers? ---------
select gender, SUM(purchase_amount) as revenue
from sales_data
group by gender;


-- Q2.  which customer used a discount but still spent more than the average purchase amount?
select customer_id, purchase_amount
from sales_data
where discount_applied = 'Yes' and purchase_amount >= (select AVG(purchase_amount) from sales_data);

-- Q3. which are the top 5 products wiht the highest average review rating?
describe sales_data;

select item_purchased, ROUND(AVG(review_rating),2) as average_product_rating
from sales_data
group by item_purchased
order by AVG(review_rating) desc
limit 5;

-- Q4. compare the average purchase amount between standard and express shipping.--
select shipping_type, ROUND(AVG(purchase_amount),2)
from sales_data
where shipping_type in ('Standard','Express')
group by shipping_type;

-- Q5. Do subscribed customers spend more? compare average spend and total revenue
-- between subscribers and non-subscribers.

select subscription_status, COUNT(customer_id) as total_sustomers,
ROUND (AVG(purchase_amount),2) as avg_spend,
ROUND (SUM(purchase_amount),2) as total_revenue
from sales_data
group by subscription_status
order by total_revenue, avg_spend desc;

-- Q6. which 5 products have the highest percentage of purchases with discounts applied ?
select item_purchased, ROUND(100 *SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)/COUNT(*),2) as discount_rate
from sales_data
group by item_purchased
order by discount_rate desc
limit 5;

-- Q7. segment customers into new, returning, adn loyal based on their total 
-- number of previous purchases, adn show the count of eachsegment.alter
with customer_type as (select customer_id, previous_purchases,
	case 
		when previous_purchases = 1 then 'New'
        when previous_purchases between 2 and 10 then 'Returning'
        else 'Loyal'
        end as customer_segment
from sales_data)
select customer_segment, count(*) as "Number of Customers"
from customer_type
group by customer_segment;

-- Q 8 what are the top 3 most purchased products within each category ?
with item_counts as 
(select category, item_purchased, COUNT(customer_id) as total_orders,
ROW_NUMBER() OVER(PARTITION BY category order by count(customer_id)desc)as item_rank
from sales_data
group by category, item_purchased)
select item_rank, category, item_purchased, total_orders
from item_counts
where item_rank<=3;

-- Q9. are customers who are repeat buyers ( more than 5 previous purchases ) also likely to subscribe?
select subscription_status,
count(customer_id) as repeat_buyers
from sales_data
where previous_purchases >5
group by subscription_status;


-- Q10. what is the revenue contribution of each age group?
select age_group,
SUM(purchase_amount) as total_revenue
from sales_data
group by age_group
order by total_revenue desc;
    
        
	
























